---
- name: Run Python Script
  hosts: all
  gather_facts: False

  tasks:
  - name: Copy file
    copy: src=scripts/test.py dest=/opt/test.py owner=root mode=755

  - name: Execute script
    command: /opt/test.py
